src/Entity/Personnes.php
<?php

namespace App\Entity;

use App\Repository\PersonnesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonnesRepository::class)
 */
class Personnes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/PersonnesType.php
<?php

namespace App\Form;

use App\Entity\Personnes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonnesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('adresse')
            ->add('ville')
            ->add('code_postal')
            ->add('description')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Personnes::class,
        ]);
    }
}

src/Controller/PersonnesController.php
<?php

namespace App\Controller;

use App\Entity\Personnes;
use App\Form\PersonnesType;
use App\Repository\PersonnesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/personnes")
 */
class PersonnesController extends AbstractController
{
    /**
     * @Route("/", name="personnes_index", methods={"GET"})
     */
    public function index(PersonnesRepository $personnesRepository): Response
    {


        return $this->render('personnes/index.html.twig', [
            'personnes' => $personnesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="personnes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $personne = new Personnes();
        $form = $this->createForm(PersonnesType::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($personne);
            $entityManager->flush();

            return $this->redirectToRoute('personnes_index');
        }

        return $this->render('personnes/new.html.twig', [
            'personne' => $personne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="personnes_show", methods={"GET"})
     */
    public function show(Personnes $personne): Response
    {
        return $this->render('personnes/show.html.twig', [
            'personne' => $personne,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="personnes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Personnes $personne): Response
    {
        $form = $this->createForm(PersonnesType::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('personnes_index');
        }

        return $this->render('personnes/edit.html.twig', [
            'personne' => $personne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="personnes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Personnes $personne): Response
    {
        if ($this->isCsrfTokenValid('delete'.$personne->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($personne);
            $entityManager->flush();
        }

        return $this->redirectToRoute('personnes_index');
    }
}

templates/personnes/_delete_form.html.twig
<form method="post" action="{{ path('personnes_delete', {'id': personne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personne.id) }}">
    <button class="btn">Delete</button>
</form>

templates/personnes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Personnes{% endblock %}

{% block body %}
    <h1>Edit Personnes</h1>

    {{ include('personnes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('personnes_index') }}">back to list</a>

    {{ include('personnes/_delete_form.html.twig') }}
{% endblock %}

templates/personnes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnes index{% endblock %}

{% block body %}
    <h1>Personnes index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th>Code_postal</th>
                <th>Description</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for personne in personnes %}
            <tr>
                <td>{{ personne.id }}</td>
                <td>{{ personne.nom }}</td>
                <td>{{ personne.adresse }}</td>
                <td>{{ personne.ville }}</td>
                <td>{{ personne.codePostal }}</td>
                <td>{{ personne.description }}</td>
                <td>{{ personne.email }}</td>
                <td>
                    <a href="{{ path('personnes_show', {'id': personne.id}) }}">show</a>
                    <a href="{{ path('personnes_edit', {'id': personne.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('personnes_new') }}">Create new</a>
{% endblock %}

templates/personnes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Personnes{% endblock %}

{% block body %}
    <h1>Create new Personnes</h1>

    {{ include('personnes/_form.html.twig') }}

    <a href="{{ path('personnes_index') }}">back to list</a>
{% endblock %}

templates/personnes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnes{% endblock %}

{% block body %}
    <h1>Personnes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personne.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ personne.nom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ personne.adresse }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ personne.ville }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ personne.codePostal }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ personne.description }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ personne.email }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('personnes_index') }}">back to list</a>

    <a href="{{ path('personnes_edit', {'id': personne.id}) }}">edit</a>

    {{ include('personnes/_delete_form.html.twig') }}
{% endblock %}